version: '3.8'
services:
  app-prod:
    container_name: app-prod
    build:
      context: .
      target: production
      dockerfile: Dockerfile.production
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"