version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: app-prod
    volumes:
      - ./dist/media:/app/dist/media
    ports:
      - '3000:3000'